spring:
  profiles:
    active: dev

# logging 설정
logging:
  level:
    root: debug
    sql: trace
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS,Asia/Seoul} [%thread] %-5level %logger{36}.%M - %msg%n"
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS,Asia/Seoul} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
  file:
    name: logs/dev_log.log

---
spring:
  profiles: dev
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/sidedish_db;
      driver-class-name: org.h2.Driver
      username: sa
      password:
  h2:
    console:
      enabled: true
---
spring:
  profiles: prod
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sidedish_db?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: sidedish08
    password: sidedish08
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always
    hikari:
      maximum-pool-size: 10
